CREATE TABLE USR (
  ID_USER INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_USER PRIMARY KEY ,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  MAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  TELEPHONE VARCHAR(15) NOT NULL UNIQUE,
  ADDRESS VARCHAR(100) NOT NULL,
  CITY VARCHAR(50) NOT NULL
);
CREATE TABLE ORDR(
  ID_ORDER INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_ORDER PRIMARY KEY,
  CITY VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  DAY_ORDERED DATE NOT NULL,
  DAY_ARRIVED DATE,
  ID_USER INT NOT NULL,
  CONSTRAINT FK_ORDER FOREIGN KEY (ID_USER) REFERENCES USR(ID_USER) 
  ); 
CREATE TABLE PRODUCT_LINE (
  ID_PRODUCT_LINE INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_PRODUCT_LINE PRIMARY KEY,
  QUANTITY INT NOT NULL,
  UNIT_PRICE DECIMAL(10,2) NOT NULL,
  ID_ORDER INT NOT NULL,
  PRIMARY KEY (ID_PRODUCT_LINE),
  CONSTRAINT FK_ID_PRODUCT_LINE FOREIGN KEY (ID_ORDER) REFERENCES `ORDER`(ID_ORDER)
);
CREATE TABLE PRODUCT (
  ID_PRODUCT INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_PRODUCT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRICE DECIMAL (10,2) NOT NULL,
  ID_PRODUCT_LINE INT NOT NULL,
  CONSTRAINT FK_ID_PRODUCT FOREIGN KEY (ID_PRODUCT_LINE) REFERENCES PRODUCT_LINE(ID_PRODUCT_LINE)
);

INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES ("Capuccino", "The perfect balance of espresso, steamed milk and foam it has a strong coffee flavor mixed with the sweetness of the milk", 0.75)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Lungo","A longer espresso with more water, resulting in a milder taste and a larger serving size",0.40)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Ristretto","A concentrated espresso shot with less water, resulting in a stronger, more intense flavor",0.60)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Latte","A milk-based coffee made with espresso and steamed milk, topped with a small layer of frothed milk",0.50)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Organic","A coffee made with organically grown beans, without the use of synthetic pesticides or fertilizers",0.55)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Decaf","A type of coffee made with decaffeinated beans, providing a similar taste to regular coffee but without the caffeine.",0.45)
INSERT VALUES INTO PRODUCT (NAME, DESCRIPTION, PRICE) VALUES("Ristretto","A concentrated espresso shot with less water, resulting in a stronger, more intense flavor",0.45)




