CREATE TABLE USR (
  ID_USER INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_USER PRIMARY KEY ,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  MAIL VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  TELEPHONE VARCHAR(15) NOT NULL UNIQUE,
  ADDRESS VARCHAR(100) NOT NULL,
  CITY VARCHAR(50) NOT NULL
);
CREATE TABLE ORDR(
  ID_ORDER INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_ORDER PRIMARY KEY,
  CITY VARCHAR(50) NOT NULL,
  COUNTRY VARCHAR(50) NOT NULL,
  DAY_ORDERED DATE NOT NULL,
  DAY_ARRIVED DATE,
  ID_USER INT NOT NULL,
  CONSTRAINT FK_ORDER FOREIGN KEY (ID_USER) REFERENCES USR(ID_USER) 
  ); 
CREATE TABLE PRODUCT_LINE (
  ID_PRODUCT_LINE INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_PRODUCT_LINE PRIMARY KEY,
  QUANTITY INT NOT NULL,
  UNIT_PRICE DECIMAL(10,2) NOT NULL,
  ID_ORDER INT NOT NULL,
  PRIMARY KEY (ID_PRODUCT_LINE),
  CONSTRAINT FK_ID_PRODUCT_LINE FOREIGN KEY (ID_ORDER) REFERENCES `ORDER`(ID_ORDER)
);
CREATE TABLE PRODUCT (
  ID_PRODUCT INT GENERATED ALWAYS AS IDENTITY(START WITH 1, INCREMENT BY 1) CONSTRAINT PK_ID_PRODUCT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(255),
  PRICE DECIMAL (10,2) NOT NULL,
  ID_PRODUCT_LINE INT NOT NULL,
  CONSTRAINT FK_ID_PRODUCT FOREIGN KEY (ID_PRODUCT_LINE) REFERENCES PRODUCT_LINE(ID_PRODUCT_LINE)
);
